import type { Metadata } from 'next';
import './globals.css';
import { Playfair_Display, Montserrat } from 'next/font/google';

const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-playfair-display',
});
const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--font-montserrat',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${playfair.variable} ${montserrat.variable} font-sans antialiased`}>
				{children}
			</body>
		</html>
	);
}
